### ISSUE TITLE
can I train LLMs using MI60

### ISSUE THREAD

**Issue by etemiz** [eliranwong/MultiAMDGPU_AIDev_Ubuntu#3]
hi,
I bought couple of MI60 32GB cards. can I train models?
I was using LLaMA-Factory but I can try other tools.
My method is fdsp_qlora.

**Comment by eliranwong** [comment]
I haven't tried Llama-factory yet.  You may also consider [llama.cpp](https://www.bing.com/search?q=llama.cpp&cvid=1fdec8f208e7490b877589c9ed3dbf3b&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgcIARDpBxhAMgYIAhAAGEAyBggDEEUYOzIHCAQQ6QcYQDIGCAUQABhAMgYIBhBFGDwyBggHEEUYPDIGCAgQRRg8MggICRDpBxj8VdIBCDI0OTZqMGo0qAIIsAIB&FORM=ANAB01&PC=U531) which comes with a fintune command.
